// components/CategoryLinkCard.tsx
import React from 'react';
import type { CategoryLinkData } from '../types';

interface CategoryLinkCardProps {
    data: CategoryLinkData;
}

const CategoryLinkCard: React.FC<CategoryLinkCardProps> = ({ data }) => {
    return (
        <li className="snap-start">
            <a href={data.link} className="block rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-shadow duration-300 relative aspect-video">
                <img src={data.imageUrl} alt={data.name} className="w-full h-full object-cover" />
                <div className="absolute inset-0 bg-black/20"></div>
                <h3 className="absolute bottom-3 left-4 text-white font-bold text-lg">{data.name}</h3>
            </a>
        </li>
    );
}

export default CategoryLinkCard;

// sveltekit/src/lib/components/CategoryLinkCard.svelte
<script lang="ts">
import type { CategoryLinkData } from "$lib/types";

const { data } = $props<{ data: CategoryLinkData }>();
</script>

<a
	class="card-interactive relative block overflow-hidden rounded-2xl"
	href={data.link}
>
	<div
		class="relative h-32 w-full bg-cover bg-center"
		style="background-image: url({data.imageUrl}); background-color: {data.accentColor}"
	>
		<div class="absolute inset-0 gradient-light" />
		<div class="absolute inset-0 flex items-center justify-center">
			<h3 class="font-bold text-text-primary text-lg">{data.name}</h3>
		</div>
	</div>
</a>
