// components/SmallLockupCard.tsx
import React from 'react';
import type { SmallLockupData } from '../types';

interface SmallLockupCardProps {
    data: SmallLockupData;
}

const SmallLockupCard: React.FC<SmallLockupCardProps> = ({ data }) => {
    return (
        <li className="snap-start">
            <a href={data.link} className="flex items-center space-x-4 group">
                {data.ordinal && <div className="text-2xl font-bold text-gray-400 w-8 text-center">{data.ordinal}</div>}
                <div className="flex-shrink-0">
                    <img src={data.iconUrl} alt={`${data.name} icon`} className="w-16 h-16 rounded-2xl" style={{ backgroundColor: data.bgColor }} />
                </div>
                <div className="flex-1 min-w-0">
                    <p className="font-semibold truncate text-black group-hover:text-blue-600">{data.name}</p>
                    <p className="text-xs text-gray-500 truncate">{data.subtitle}</p>
                </div>
                <div className="flex-shrink-0">
                    <button className="px-5 py-1.5 rounded-full text-sm font-semibold text-blue-600 bg-gray-100 group-hover:bg-gray-200 transition">
                        View
                    </button>
                </div>
            </a>
        </li>
    );
};

export default SmallLockupCard;

// sveltekit/src/lib/components/SmallLockupCard.svelte
<script lang="ts">
import type { SmallLockupData } from "$lib/types";

const { data } = $props<{ data: SmallLockupData }>();
</script>

<li class="snap-start">
	<a class="group flex items-center space-x-4" href={data.link}>
		{#if data.ordinal}
			<div class="w-8 text-center font-bold text-2xl text-text-secondary">
				{data.ordinal}
			</div>
		{/if}
		<div class="flex-shrink-0">
			<img
				alt={`${data.name} icon`}
				class="h-16 w-16 rounded-2xl"
				height={64}
				src={data.iconUrl}
				style="background-color: {data.bgColor}"
				width={64}
			/>
		</div>
		<div class="min-w-0 flex-1">
			<p class="truncate font-semibold text-text-primary group-hover:text-link">
				{data.name}
			</p>
			<p class="truncate text-text-secondary text-xs">{data.subtitle}</p>
		</div>
		<div class="flex-shrink-0">
			<button
				class="rounded-full bg-background-disabled px-5 py-1.5 font-semibold text-link text-sm transition group-hover:bg-background-hover"
				type="button"
			>
				View
			</button>
		</div>
	</a>
</li>
