// sveltekit/src/lib/components/CategoryLinkCard.svelte
<script lang="ts">
import type { CategoryLinkData } from "$lib/types";

const { data } = $props<{ data: CategoryLinkData }>();
</script>

<a
	class="card-interactive relative block overflow-hidden rounded-2xl"
	href={data.link}
>
	<div
		class="relative h-32 w-full bg-cover bg-center"
		style="background-image: url({data.imageUrl}); background-color: {data.accentColor}"
	>
		<div class="absolute inset-0 gradient-light" />
		<div class="absolute inset-0 flex items-center justify-center">
			<h3 class="font-bold text-text-primary text-lg">{data.name}</h3>
		</div>
	</div>
</a>

// components/category-link-card.tsx
import type React from "react";
import type { CategoryLinkData } from "../types";

type CategoryLinkCardProps = {
  data: CategoryLinkData;
};

const CategoryLinkCard: React.FC<CategoryLinkCardProps> = ({ data }) => (
  <li className="snap-start">
    <a
      className="relative block aspect-video overflow-hidden rounded-lg shadow-md transition-shadow duration-300 hover:shadow-lg"
      href={data.link}
    >
      <img
        alt={data.name}
        className="h-full w-full object-cover"
        height={160}
        src={data.imageUrl}
        width={284}
      />
      <div className="absolute inset-0 bg-black/20" />
      <h3 className="absolute bottom-3 left-4 font-bold text-lg text-white">
        {data.name}
      </h3>
    </a>
  </li>
);

export default CategoryLinkCard;
