// sveltekit/src/lib/components/HeroCarousel.svelte
<script lang="ts">
import type { CategoryShelfItem } from "$lib/types";

const { items } = $props<{ items: CategoryShelfItem[] }>();

let currentIndex = $state(0);

function _nextSlide() {
	currentIndex = (currentIndex + 1) % items.length;
}

function _prevSlide() {
	currentIndex = (currentIndex - 1 + items.length) % items.length;
}

const _currentItem = $derived(items[currentIndex]);
</script>

<section class="relative mb-section overflow-hidden rounded-2xl">
	<div class="relative h-96">
		{#if currentItem.imageUrl}
			<img
				alt={currentItem.title}
				class="h-full w-full object-cover"
				src={currentItem.imageUrl}
			/>
		{/if}
		<div class="absolute inset-0 gradient-dark" />
		<div class="absolute bottom-8 left-8 right-8">
			{#if currentItem.badge}
				<span class="mb-2 inline-block rounded-full bg-primary/10 px-3 py-1 text-primary text-sm font-medium">
					{currentItem.badge}
				</span>
			{/if}
			<h2 class="mb-2 font-bold text-text-light text-3xl">{currentItem.title}</h2>
			{#if currentItem.subtitle}
				<p class="text-text-light/90 text-lg">{currentItem.subtitle}</p>
			{/if}
		</div>
	</div>

	{#if items.length > 1}
		<button
			class="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-black/50 p-2 text-white hover:bg-black/70"
			onclick={prevSlide}
		>
			<svg
				class="h-6 w-6"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				viewBox="0 0 24 24"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path d="M15 19l-7-7 7-7" />
			</svg>
		</button>
		<button
			class="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-black/50 p-2 text-white hover:bg-black/70"
			onclick={nextSlide}
		>
			<svg
				class="h-6 w-6"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				viewBox="0 0 24 24"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path d="M9 5l7 7-7 7" />
			</svg>
		</button>

		<div class="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2">
			{#each items as _, index (index)}
				<button
					class="h-2 w-2 rounded-full transition-colors {index === currentIndex
						? 'bg-white'
						: 'bg-white/50'}"
					onclick={() => currentIndex = index}
				/>
			{/each}
		</div>
	{/if}
</section>

// components/hero-carousel.tsx
import type React from "react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { SpotlightCardData } from "../types";
import AppLockup from "./app-lockup";

type HeroCarouselProps = {
  items: SpotlightCardData[];
};

const HeroCard: React.FC<{ data: SpotlightCardData; isActive: boolean }> = ({
  data,
  isActive,
}) => {
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    if (videoRef.current) {
      if (isActive) {
        videoRef.current
          .play()
          .catch((e) => console.error("Video play failed:", e));
      } else {
        videoRef.current.pause();
        videoRef.current.currentTime = 0;
      }
    }
  }, [isActive]);

  const cardThemeClass = data.theme === "dark" ? "text-white" : "text-black";

  return (
    <div className="w-full flex-shrink-0">
      <div className="relative aspect-[1.7] w-full md:aspect-[2.2] lg:aspect-[2.5] xl:aspect-[3]">
        <a className="block h-full w-full" href={data.link}>
          {data.videoSrc ? (
            <video
              className="h-full w-full object-cover"
              loop
              muted
              playsInline
              poster={data.videoPosterUrl}
              ref={videoRef}
              src={data.videoSrc}
            />
          ) : (
            <img
              alt={data.title}
              className="h-full w-full object-cover"
              height={600}
              src={data.imageUrl}
              width={800}
            />
          )}

          <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent" />

          <div
            className={`absolute inset-0 flex flex-col justify-between p-6 md:p-8 ${cardThemeClass}`}
          >
            <div>
              <p className="font-bold text-xs uppercase tracking-wider opacity-90">
                {data.badge}
              </p>
              <h2 className="mt-1 font-bold text-3xl lg:text-4xl">
                {data.title}
              </h2>
              <p className="mt-1 max-w-xs text-sm opacity-90">
                {data.subtitle}
              </p>
            </div>
            <div className="max-w-sm">
              <AppLockup {...data.appInfo} theme={data.theme} />
            </div>
          </div>
        </a>
      </div>
    </div>
  );
};

const HeroCarousel: React.FC<HeroCarouselProps> = ({ items }) => {
  const [activeIndex, setActiveIndex] = useState(0);
  const scrollRef = useRef<HTMLDivElement>(null);
  // Fix: Replace Node-specific type with a portable type to resolve namespace error.
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const resetTimeout = useCallback(() => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }
  }, []);

  const scrollToIndex = useCallback(
    (index: number) => {
      if (scrollRef.current) {
        const scrollWidth = scrollRef.current.scrollWidth;
        const childWidth = scrollWidth / items.length;
        scrollRef.current.scrollTo({
          left: childWidth * index,
          behavior: "smooth",
        });
        setActiveIndex(index);
      }
    },
    [items.length]
  );

  useEffect(() => {
    resetTimeout();
    timeoutRef.current = setTimeout(
      () => scrollToIndex((activeIndex + 1) % items.length),
      5000
    );

    return () => {
      resetTimeout();
    };
  }, [activeIndex, items.length, resetTimeout, scrollToIndex]);

  const handleScroll = () => {
    if (scrollRef.current) {
      const { scrollLeft, clientWidth } = scrollRef.current;
      const newIndex = Math.round(scrollLeft / clientWidth);
      if (newIndex !== activeIndex) {
        setActiveIndex(newIndex);
      }
    }
  };

  const nextSlide = () => {
    const newIndex = (activeIndex + 1) % items.length;
    scrollToIndex(newIndex);
  };

  const prevSlide = () => {
    const newIndex = (activeIndex - 1 + items.length) % items.length;
    scrollToIndex(newIndex);
  };

  return (
    <section className="group relative mb-8">
      <div className="absolute inset-x-0 top-0 h-full overflow-hidden">
        <div className="relative h-full w-full">
          {items.map((item, index) => (
            <div
              className="absolute inset-0 transition-opacity duration-700 ease-in-out"
              key={item.id}
              style={{
                opacity: index === activeIndex ? 1 : 0,
                backgroundColor: item.accentColor,
              }}
            >
              <img
                alt=""
                aria-hidden="true"
                className="h-full w-full scale-125 object-cover opacity-30"
                height={800}
                src={item.videoPosterUrl || item.imageUrl}
                style={{ filter: "blur(40px)" }}
                width={1200}
              />
              <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[#f5f5f7]" />
            </div>
          ))}
        </div>
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div
          className="scrollbar-hide flex snap-x snap-mandatory overflow-x-auto rounded-xl shadow-xl"
          onScroll={handleScroll}
          ref={scrollRef}
        >
          {items.map((item, index) => (
            <HeroCard
              data={item}
              isActive={index === activeIndex}
              key={item.id}
            />
          ))}
        </div>

        <button
          className="-translate-y-1/2 absolute top-1/2 left-2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/20 text-white opacity-0 backdrop-blur-sm transition-all duration-300 hover:bg-white/30 focus:outline-none focus:ring-2 focus:ring-white group-hover:opacity-100 sm:left-6 lg:left-12"
          onClick={prevSlide}
          type="button"
        >
          <span className="sr-only">Previous Slide</span>
          <svg
            aria-hidden="true"
            className="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <title>Chevron left</title>
            <path
              d="M15 19l-7-7 7-7"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="3"
            />
          </svg>
        </button>
        <button
          className="-translate-y-1/2 absolute top-1/2 right-2 z-10 flex h-10 w-10 items-center justify-center rounded-full bg-white/20 text-white opacity-0 backdrop-blur-sm transition-all duration-300 hover:bg-white/30 focus:outline-none focus:ring-2 focus:ring-white group-hover:opacity-100 sm:right-6 lg:right-12"
          onClick={nextSlide}
          type="button"
        >
          <span className="sr-only">Next Slide</span>
          <svg
            aria-hidden="true"
            className="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <title>Chevron right</title>
            <path
              d="M9 5l7 7-7 7"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="3"
            />
          </svg>
        </button>
        <div className="-translate-x-1/2 absolute bottom-4 left-1/2 flex space-x-2">
          {items.map((item, index) => (
            <button
              className={`h-2 w-2 rounded-full transition-colors ${index === activeIndex ? "bg-white/80" : "bg-white/30"}`}
              key={item.id}
              onClick={() => scrollToIndex(index)}
              type="button"
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default HeroCarousel;
