// sveltekit/src/lib/components/SpotlightCard.svelte
<script lang="ts">
import type { SpotlightCardData } from "$lib/types";

const { data } = $props<{ data: SpotlightCardData }>();
</script>

<a
	class="card-interactive relative block overflow-hidden rounded-2xl {data.layout === 'west' ? 'md:flex md:flex-row' : ''}"
	href={data.link}
>
	<div
		class="relative bg-cover bg-center {data.layout === 'west' ? 'md:w-1/2' : 'h-48'}"
		style="background-image: url({data.imageUrl}); background-color: {data.accentColor}"
	>
		<div class="absolute inset-0 gradient-dark" />
		<div class="absolute bottom-4 left-4 right-4">
			{#if data.badge}
				<span class="mb-2 inline-block rounded-full bg-primary/10 px-2 py-1 text-primary text-xs font-medium">
					{data.badge}
				</span>
			{/if}
			<h3 class="mb-1 font-bold text-text-light text-lg">{data.title}</h3>
			<p class="text-text-light/80 text-sm">{data.subtitle}</p>
		</div>
	</div>
	{#if data.appInfo}
		<div class="p-4 {data.layout === 'west' ? 'md:w-1/2' : ''}">
			<AppLockup appInfo={data.appInfo} />
		</div>
	{/if}
</a>

// components/SpotlightCard.tsx
import React from 'react';
import type { SpotlightCardData } from '../types';
import AppLockup from './AppLockup';

interface SpotlightCardProps {
    data: SpotlightCardData;
}

const SpotlightCard: React.FC<SpotlightCardProps> = ({ data }) => {
    const cardThemeClass = data.theme === 'dark' ? 'dark-theme-card' : 'light-theme-card';

    return (
        <li className="snap-start w-full flex-shrink-0">
            <a
                href={data.link}
                className="block rounded-xl overflow-hidden shadow-lg hover:shadow-2xl transition-shadow duration-300 ease-in-out transform hover:-translate-y-1 relative aspect-[1.8] md:aspect-[2.5] lg:aspect-[2.8]"
                style={{ backgroundColor: data.accentColor }}
            >
                <div className={`relative ${cardThemeClass} h-full flex flex-col`}>
                    <img src={data.imageUrl} alt={data.title} className="absolute top-0 left-0 w-full h-full object-cover" />
                    <div 
                        className="absolute inset-0"
                        style={{ background: `linear-gradient(90deg, ${data.accentColor} 35%, transparent 70%)` }}
                    ></div>

                    <div className="relative p-6 flex flex-col justify-between h-full w-full md:w-1/2 lg:w-2/5">
                        <div>
                            <p className="text-xs font-bold uppercase tracking-wider opacity-80">{data.badge}</p>
                            <h3 className="text-2xl md:text-3xl font-bold mt-1 line-clamp-2">{data.title}</h3>
                            <p className="text-sm opacity-80 mt-1 line-clamp-2">{data.subtitle}</p>
                        </div>
                        <AppLockup {...data.appInfo} theme={data.theme} />
                    </div>
                </div>
            </a>
        </li>
    );
};

export default SpotlightCard;
