// sveltekit/src/lib/components/TodayCard.svelte
<script lang="ts">
import type { CardData } from "$lib/types";

const { card } = $props<{ card: CardData }>();
</script>

<a
	class="card-interactive relative block overflow-hidden rounded-2xl"
	href={card.link}
>
	{#if card.videoSrc}
		<video
			class="h-48 w-full object-cover"
			poster={card.videoPosterUrl}
			preload="metadata"
		>
			<source src={card.videoSrc} type="video/mp4" />
			<track kind="captions" srcLang="en" label="English captions" />
		</video>
	{:else if card.titleImage}
		<img
			alt={card.title}
			class="h-48 w-full object-cover"
			src={card.titleImage}
		/>
	{:else if card.imageUrl}
		<img
			alt={card.title}
			class="h-48 w-full object-cover"
			src={card.imageUrl}
		/>
	{/if}

	<div class="p-4">
		{#if card.badge}
			<span class="mb-2 inline-block rounded-full bg-primary/10 px-2 py-1 text-primary text-xs font-medium">
				{card.badge}
			</span>
		{/if}
		<h3 class="mb-1 font-bold text-text-primary text-lg">{card.title}</h3>
		{#if card.description}
			<p class="text-text-secondary text-sm">{card.description}</p>
		{/if}
	</div>

	{#if card.lockupList && card.lockupList.length > 0}
		<div class="border-t border-border p-4">
			<div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
				{#each card.lockupList as app (app.name)}
					<div class="flex items-center gap-2">
						<img
							alt={app.name}
							class="h-8 w-8 rounded-lg"
							src={app.iconUrl}
						/>
						<div class="min-w-0 flex-1">
							<p class="truncate font-medium text-text-primary text-sm">{app.name}</p>
							<p class="text-text-secondary text-xs">{app.subtitle}</p>
						</div>
					</div>
				{/each}
			</div>
		</div>
	{/if}
</a>

// components/today-card.tsx
import type React from "react";
import { Fragment, useEffect, useRef, useState } from "react";
import type { CardData } from "../types";
import AppLockup from "./app-lockup";

type TodayCardProps = {
  data: CardData;
};

const TodayCard: React.FC<TodayCardProps> = ({ data }) => {
  const MAX_LOCKUP_DISPLAY = 5;
  const [isHovered, setIsHovered] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    if (videoRef.current) {
      if (isHovered) {
        videoRef.current
          .play()
          .catch((error) => console.log("Video play failed:", error));
      } else {
        videoRef.current.pause();
        videoRef.current.currentTime = 0;
      }
    }
  }, [isHovered]);

  const cardThemeClass =
    data.theme === "dark" ? "dark-theme-card" : "light-theme-card";
  const gradientClass =
    data.theme === "dark" ? "with-gradient-dark" : "with-gradient-light";

  const hasLockup = data.appInfo || data.lockupList;

  const renderMultilineTitle = (text: string) =>
    text.split("<br>").map((segment, index) => (
      <Fragment key={`${data.id}-title-${index}`}>
        {index > 0 && <br />}
        {segment}
      </Fragment>
    ));

  return (
    <a
      className="card-interactive relative block transform overflow-hidden"
      href={data.link}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      style={{ backgroundColor: data.accentColor }}
    >
      <div className={`relative ${cardThemeClass} flex h-full flex-col`}>
        {/* Background Media */}
        <div className="relative aspect-card w-full overflow-hidden">
          {data.videoSrc ? (
            <video
              className="absolute inset-0 h-full w-full object-cover"
              loop
              muted
              playsInline
              poster={data.videoPosterUrl}
              ref={videoRef}
              src={data.videoSrc}
            />
          ) : (
            <img
              alt={data.title}
              className="absolute inset-0 h-full w-full object-cover"
              height={500}
              src={data.imageUrl}
              width={400}
            />
          )}
        </div>

        {/* Text and Lockup Overlay */}
        <div
          className={`absolute inset-0 flex flex-col justify-between p-card ${hasLockup ? gradientClass : ""}`}
        >
          {/* Top Text */}
          <div>
            <p className="font-bold text-badge uppercase tracking-wider opacity-80">
              {data.badge}
            </p>
            {data.titleImage ? (
              <img
                alt={data.title}
                className="mt-6 w-4/5"
                height={100}
                src={data.titleImage}
                width={300}
              />
            ) : (
              <h3 className="mt-content font-bold text-2xl leading-tight">
                {renderMultilineTitle(data.title)}
              </h3>
            )}

            <p className="mt-content line-clamp-2 text-sm opacity-80">
              {data.description}
            </p>
          </div>

          {/* Bottom Lockup */}
          {data.appInfo && (
            <div className="z-overlay">
              <AppLockup {...data.appInfo} theme={data.theme} />
            </div>
          )}
          {data.lockupList && (
            <div className="z-overlay flex gap-2">
              {data.lockupList.slice(0, MAX_LOCKUP_DISPLAY).map((app) => (
                <button
                  className="block cursor-pointer border-none bg-transparent p-0 transition-transform hover:scale-105"
                  key={app.name}
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    window.open(app.link, "_blank");
                  }}
                  type="button"
                >
                  <img
                    alt={app.name}
                    className="size-app-icon rounded-xl"
                    height={48}
                    src={app.iconUrl}
                    width={48}
                  />
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </a>
  );
};

export default TodayCard;
