// pages/games.tsx
import type React from "react";
import Shelf from "../components/shelf";
import { gamesShelfData } from "../constants";
import type { ShelfData } from "../types";

const Games: React.FC = () => (
  <main className="flex-1 bg-surface md:pr-4 md:pl-8 lg:px-8 xl:px-12">
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 md:px-0">
      <h1 className="mb-header font-bold text-4xl text-text-primary">Games</h1>
      <div className="gap-section space-y-12">
        {gamesShelfData.map((shelf: ShelfData) => (
          <Shelf
            cardLayout={shelf.cardLayout}
            cards={shelf.cards}
            key={shelf.id}
            subtitle={shelf.subtitle}
            title={shelf.title}
          />
        ))}
      </div>
    </div>
  </main>
);

export default Games;

// sveltekit/src/routes/games/+page.svelte
<script lang="ts">
	import MainContent from "$lib/components/MainContent.svelte";
	import Shelf from "$lib/components/Shelf.svelte";
	import { gamesPageData } from "$lib/constants";

	const pageData = $state(gamesPageData);
</script>

<MainContent>
	<h1
		class="font-[var(--font-weight-bold)] text-[var(--color-text-primary)] text-[var(--font-size-4xl)]"
		style="margin-bottom: var(--spacing-header-margin)"
	>
		{pageData.title}
	</h1>
	<div class="gap-section space-y-12">
		{#each pageData.shelves as shelf (shelf.id)}
			<Shelf
				title={shelf.title}
				subtitle={shelf.subtitle}
				cards={shelf.cards}
				cardLayout={shelf.cardLayout}
			/>
		{/each}
	</div>
</MainContent>
